apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: online-auction
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "085279"
  MYSQL_DATABASE: "online"
  MYSQL_USER: "auction_user"
  MYSQL_PASSWORD: "085279"

