apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: online-auction
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "085279"
  # Add other sensitive data here
  # SPRING_MAIL_USERNAME: "your-email@gmail.com"
  # SPRING_MAIL_PASSWORD: "your-app-password"

